// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3uG3f3qmhjCiYK8KKVRY5nRXRGRCo1Gc',
    appId: '1:649209585701:web:d767aad0c2d8fb2ae2dfcc',
    messagingSenderId: '649209585701',
    projectId: 'nginepyuk-47745',
    authDomain: 'nginepyuk-47745.firebaseapp.com',
    storageBucket: 'nginepyuk-47745.appspot.com',
    measurementId: 'G-6ERM9EQDCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU52HrkbtmI7rgl4s47TReHEWhy7td4Z8',
    appId: '1:649209585701:android:5388875452d4e12ae2dfcc',
    messagingSenderId: '649209585701',
    projectId: 'nginepyuk-47745',
    storageBucket: 'nginepyuk-47745.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcjUjmdZ7tZsGX6WDT-tV0jQb9Z7BA-5Y',
    appId: '1:649209585701:ios:1a2966dbc613ae80e2dfcc',
    messagingSenderId: '649209585701',
    projectId: 'nginepyuk-47745',
    storageBucket: 'nginepyuk-47745.appspot.com',
    iosClientId:
        '649209585701-p76meo949q9lqa3pt2vdvrikcc9rbjmj.apps.googleusercontent.com',
    iosBundleId: 'com.example.nginepyuk',
  );
}
